/* Generated by RuntimeBrowser
 Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */
@import Foundation;
@import SceneKit;

@interface AVTAvatar : NSObject <NSCopying, SCNSceneRendererDelegate>

@end
