/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit


@import Foundation;

@class AVTAvatarInstance;

@interface AVTPuppet: NSObject
+ (id)puppetNamed:(id)arg1 options:(id)arg2;
+ (id)puppetNames;
+ (UIImage *)thumbnailForPuppetNamed:(id)arg1 options:(id)arg2;
@end
*/
/* Generated by RuntimeBrowser
 Image: /System/Library/PrivateFrameworks/AvatarKit.framework/AvatarKit
 */
@import SceneKit;
#import <CarPlay/CarPlay.h>

@class AVTAvatarInstance;

@interface AVTAnimoji : NSObject

+ (id)_pathForPuppetNamed:(id)arg1 inAvatarBundle:(bool)arg2;
+ (id)animoji;
+ (id)animojiNamed:(id)arg1;
+ (id)animojiNames;
+ (id)animojiWithContentsOfURL:(id)arg1;
+ (unsigned char)classIdentifier;
+ (void)preloadAnimojiNamed:(id)arg1;
+ (void)preloadPuppet:(id)arg1;
+ (void)preloadPuppetNamed:(id)arg1;
+ (id)puppetNamed:(id)arg1 options:(id)arg2;
+ (id)puppetNames;
+ (UIImage *)thumbnailForAnimojiNamed:(id)arg1 options:(id)arg2;
+ (UIImage *)thumbnailForPuppetNamed:(id)arg1 options:(id)arg2;

@end

@interface AVTMemoji : NSObject

+ (id)neutralMemoji;
+ (id)memoji;
+ (id)memojiWithContentsOfURL:(id)arg1 error:(id*)arg2;
@end


@interface AVTResourceLocator : NSObject

+ (id)sharedResourceLocator;

- (id)animojiResourcesURL;
- (id)componentsURL;
- (id)maskImagesURL;
- (id)materialsURL;
- (id)memojiResourcesURL;
- (id)pathForAnimojiResource:(id)arg1 ofType:(id)arg2;
- (id)pathForAnimojiResource:(id)arg1 ofType:(id)arg2 inDirectory:(id)arg3;
- (id)pathForMemojiResource:(id)arg1 ofType:(id)arg2;
- (id)pathForMemojiResource:(id)arg1 ofType:(id)arg2 inDirectory:(id)arg3;
- (id)presetThumbnailsURL;
- (id)propsURL;
- (id)resourcesURL;

@end
